cc_library(
  name = "common",
  srcs = [
    "common.cc"
  ]
)

cc_library(
  name = "ttcp_cli",
  srcs = [
    "ttcp_client.cc"
  ]
)

cc_library(
  name = "ttcp_serv",
  srcs = [
    "ttcp_server.cc"
  ]
)
