/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"git@github.com:MaxEntroy/pnp.git\n"
"* main\n"
"commit a4cf0ae8d697726f066972269111d1b300ab630d\n"
"Author: MaxEntroy <likang@tju.edu.cn>\n"
"Date:   Tue Apr 27 14:45:51 2021 +0800\n"
"\n"
"    Update README in ep04.\n"
""};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Wed Apr 28 11:58:22 2021";
extern const char kBuilderName[] = "kang";
extern const char kHostName[] = "ubuntu";
extern const char kCompiler[] = "GCC 4.8";
}}
