/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"git@github.com:MaxEntroy/pnp.git\n"
"* main\n"
"commit 8d0b56a5d731dbba04ce030fcedd78bf2ca5d9b9\n"
"Author: MaxEntroy <likang@tju.edu.cn>\n"
"Date:   Wed Apr 28 11:58:57 2021 +0800\n"
"\n"
"    Add demo-00 in ep04.\n"
""};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Mon May 10 11:48:08 2021";
extern const char kBuilderName[] = "kang";
extern const char kHostName[] = "ubuntu";
extern const char kCompiler[] = "GCC 4.8";
}}
